SELECT * FROM CLIENTS INNER JOIN AGENTS ON CLIENTS.A_ID=AGENTS.A_ID;

SELECT * FROM DEPARTMENTS INNER JOIN MANAGER ON DEPARTMENTS.Manager_ID=MANAGER.MANAGERID;

SELECT CLIENTS.C_LNAME,CLIENTS.C_FNAME,CLIENTS.C_MI,AGENTS.A_LNAME,AGENTS.A_FNAME,AGENTS.A_MI FROM CLIENTS INNER JOIN AGENTS ON CLIENTS.A_ID=AGENTS.A_ID;

SELECT CLIENTS.C_LNAME,CLIENTS.C_FNAME,CLIENTS.C_MI,DEPARTMENTS.DESCRIPTION FROM CLIENTS INNER JOIN AGENTS ON CLIENTS.A_ID=AGENTS.A_ID INNER JOIN DEPARTMENTS ON AGENTS.A_DEPTID=DEPARTMENTS.DEPTID;

SELECT * FROM CLIENTS;
SELECT * FROM AGENTS;
SELECT * FROM DEPARTMENTS;
SELECT * FROM MANAGER;

SELECT A_Lname, A_Fname,A_MI, C_Lname, C_Fname, C_Mi, Description FROM CLIENTS 
INNER JOIN AGENTS ON CLIENTS.A_ID=AGENTS.A_ID,
INNER JOIN DEPARTMENTS ON CLIENTS.A_ID=DEPARTMENT.DeptID;



select count(*) as total from clients;

SELECT agents.A_Lname,agents.A_Fname,agents.A_Mi, count(CLIENTS.C_Fname) as total from CLIENTS INNER JOIN AGENTS on CLIENTS.A_ID = AGENTS.A_ID group by CLIENTS.A_ID;
